---
- name: Update Tellmon PostgreSQL password
  hosts: all
  become: true
  tasks:
    - name: Import update PostgreSQL password tasks
      ansible.builtin.import_tasks: update-postgres-password-tasks.yml
